# Generated by Django 5.0.4 on 2024-04-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotesapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quotes",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotesapp.author",
            ),
        ),
        migrations.AlterField(
            model_name="quotes",
            name="quote",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
